### PR TITLE
Us31 list view

### PR DESCRIPTION
**Pull request by majluni**

### CODE REVIEW

**Review by zlmonroe — CHANGES_REQUESTED** [review]
Do not merge into master

**Comment by vcedgar** [comment]
> Do not merge into master

I have fixed that

**Comment by majluni** [comment]
Is it ok now?

**Review by zlmonroe — COMMENTED** [review]
What is this branch intended to do? It looks like only the "+" node can be dragged over, and can only create more root elements, is that correct? It also currently gives an error in the Console when any other node is dragged.

**Comment by majluni** [comment]
I was only trying it out on the addition node. I have a new branch based off of this one with dev merged that adds it to all of them and lets you move the nodes around

**Comment by zlmonroe** [comment]
Does that mean that this branch is not needed? Did you split off from this branch? If so, what branch is that? If you haven't pushed it to the remote, you should just merge it into this one and push that so that we don't have a bunch of branches for the same US.

**Comment by majluni** [comment]
I suppose not. Just wanted to update everyone with it. But it's US31-DragAndDrop

**Pull request closed without merging**
